# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.
  # Example ROS Image topic stream
  stream1:
    type: topic  # topic - Image is sourced from a sensor_msgs::Image topic
    source: /unity/camera/rgb  # The ROS topic to subscribe to
    mountpoint: /back      # Choose the mountpoint for the rtsp stream. This will be able to be accessed from rtsp://<server_ip>/back
    caps: video/x-raw,framerate=10/1,width=640,height=480  # Set the caps to be applied after getting the ROS Image and before the x265 encoder.
    bitrate: 500

  overhead1:
    type: topic  # topic - Image is sourced from a sensor_msgs::Image topic
    source: /camera/overhead  # The ROS topic to subscribe to
    mountpoint: /overhead1      # Choose the mountpoint for the rtsp stream. This will be able to be accessed from rtsp://<server_ip>/back
    caps: video/x-raw,framerate=10/1,width=640,height=480  # Set the caps to be applied after getting the ROS Image and before the x265 encoder.
    bitrate: 500

  overhead2:
    type: topic  # topic - Image is sourced from a sensor_msgs::Image topic
    source: /camera/overhead/compressed  # The ROS topic to subscribe to
    mountpoint: /overhead2      # Choose the mountpoint for the rtsp stream. This will be able to be accessed from rtsp://<server_ip>/back
    caps: video/x-raw,framerate=10/1,width=640,height=480  # Set the caps to be applied after getting the ROS Image and before the x265 encoder.
    bitrate: 500

  stream2:
    type: topic  # topic - Image is sourced from a sensor_msgs::Image topic
    source: /unity/camera/rgb/image_raw  # The ROS topic to subscribe to
    mountpoint: /image_raw      # Choose the mountpoint for the rtsp stream. This will be able to be accessed from rtsp://<server_ip>/back
    caps: video/x-raw,framerate=10/1,width=640,height=480  # Set the caps to be applied after getting the ROS Image and before the x265 encoder.
    bitrate: 500

  stream3:
    type: topic  # topic - Image is sourced from a sensor_msgs::Image topic
    source: /unity/camera/depth/image_raw  # The ROS topic to subscribe to
    mountpoint: /depth      # Choose the mountpoint for the rtsp stream. This will be able to be accessed from rtsp://<server_ip>/back
    caps: video/x-raw,framerate=10/1,width=640,height=480  # Set the caps to be applied after getting the ROS Image and before the x265 encoder.
    bitrate: 500

